### ISSUE TITLE
NSURLErrorDomain error -999

### ISSUE THREAD

**Issue by reyco1** [PhantomAppDevelopment/firebase-as3#1]
Is anyone else getting this issue on the FederatedExample.mxml example while implementing it on AIR on iOS?

Error #2044: Unhandled ErrorEvent:. text=The operation couldn’t be completed. (NSURLErrorDomain error -999.)

These are my AppTransportSecurity nodes in my iOS Info Additions in the app description xml file:

`key>NSAppTransportSecurity</key>
            <dict>
                <key>NSExceptionDomains</key>
                <dict>
                    <key>firebaseio.com</key>
                    <dict>
                        <key>NSExceptionAllowsInsecureHTTPLoads</key>
                        <true/>
                        <key>NSIncludesSubdomains</key>
                        <true/>
                        <key>NSExceptionRequiresForwardSecrecy</key>
                        <true/>
                    </dict>
                    <key>googleapis.com</key>
                    <dict>
                        <key>NSExceptionAllowsInsecureHTTPLoads</key>
                        <true/>
                        <key>NSIncludesSubdomains</key>
                        <true/>
                        <key>NSExceptionRequiresForwardSecrecy</key>
                        <true/>
                    </dict>
                    <key>firebaseapp.com</key>
                    <dict>
                        <key>NSExceptionAllowsInsecureHTTPLoads</key>
                        <true/>
                        <key>NSIncludesSubdomains</key>
                        <true/>
                        <key>NSExceptionRequiresForwardSecrecy</key>
                        <true/>
                    </dict>
                    <key>facebook.com</key>
                    <dict>
                        <key>NSExceptionAllowsInsecureHTTPLoads</key>
                        <true/>
                        <key>NSIncludesSubdomains</key>
                        <true/>
                        <key>NSExceptionRequiresForwardSecrecy</key>
                        <true/>
                    </dict>
                </dict>
            </dict>`

**Comment by agentphantom** [comment]
Thanks for reporting this issue.

At which step do you get this error?

**Comment by reyco1** [comment]
Actually, I noticed that this only happens when I authenticate and then leave the app and come in and authenticate again. I guess I need to store locally that the user has already authenticated and not try to authenticate again. I've looked all over the internet to see what the REST api is for firebase to check if the user is already authenticated.

**Comment by agentphantom** [comment]
That's right, you need to store the logged in user information. You can use SharedObject or the FileStream class.

The Firebase access_token (in this guide is mostly known as idToken) has an expiration of 60 mins (the user is logged in until the token expires).

I recommend that every time you reopen your app to generate a fresh token using the Refresh Token method.
1. Fresh Install
2. Sign in with Facebook.
3. Store the JSON object into a file.
4. Exchange the idToken from that object for an access_token, save again the profile with this token so you can reuse it later.
5. When you start the app check if the file exists and if it contains valid profile information.
6. If the profile is valid, request a fresh token.
7. If the profile doesn't exist, redirect the user to the Sign In screen (Step 2).

The idea is to keep the user logged in as long as possible without prompting to re authenticate with Facebook/Google/Twitter.

This may vary depending on case by case basis, but that's the general idea.

**Comment by reyco1** [comment]
I'm having trouble doing step #6 with federated login. I see how you do it with email login in the ToDos project but what endpoint should I use to refresh the token for Facebook, for example?

**Comment by agentphantom** [comment]
The Refresh Token endpoint is the same for all the providers.
https://github.com/PhantomAppDevelopment/firebase-as3/tree/master/auth#refreshing-the-idtoken

It's a bit confusing, so I will explain it:

When you log-in/sign-in, you receive a JSON response with several values. One of them is the idToken, this idToken doesn't work with Database or Storage, only for further Auth requests.

You call the refresh token endpoint with this idToken and you will receive an access_token. What I do is to save this access_token as the new idToken since it works for future Auth, Storage and Database requests.

**Comment by reyco1** [comment]
Yeah, but then if you want to refresh again and use the new idToken (which is now the access_token value) I get this:

[trace] [FirebaseService] {
[trace]   "error": {
[trace]     "code": 400,
[trace]     "message": "INVALID_ID_TOKEN",
[trace]     "status": "INVALID_ARGUMENT"
[trace]   }
[trace] }

Should I not just save it a the oauthAccessToken instead?

**Comment by agentphantom** [comment]
You are totally right. You need to store the access_token indepently from the profile.

I have updated all the guides and examples to reflect this point.

**Comment by reyco1** [comment]
Awesome!
