### ISSUE TITLE
Getting Google And Facebook tokens

### ISSUE THREAD

**Issue by sfxworks** [PhantomAppDevelopment/firebase-as3#12]
This is sort of related. I am trying to get google and facebook auth tokens to use so I can pass to a java firebase ane. I have been trying to pass the auth-tokens I get from signing in but they aren't working. Is this because I'm getting firebase's auth tokens and not the providers? If so..can you explain to me how I can get these?

**Comment by agentphantom** [comment]
I haven't tested this but I think it is possible.

After you sign in with Facebook/Google/Twitter using Firebase and get the JSON response, there's a key named: oauthAccessToken, this might be the one you need for your ANE.
