### ISSUE TITLE
Delete is not Deleting

### ISSUE THREAD

**Issue by sfxworks** [PhantomAppDevelopment/firebase-as3#18]
As I am basing everything off of your wiki tutorials, I am trying to delete a node.

https://github.com/sfxworks/FirebaseREST/blob/master/src/net/sfxworks/firebaseREST/Database.as

using the deleteNode method, I pass in my node URL (path/to/node) and it adds the .json and auth at the end of the URL. I get a null response yet the node is not deleted. What is happening?

**Comment by agentphantom** [comment]
This is strange, does it happen with and without auth?

As far as I know when you get the 'null' response, that means the node was successfully deleted.

**Comment by sfxworks** [comment]
I'm baffled. It wants to work today apparently.
