### ISSUE TITLE
Messaging?

### ISSUE THREAD

**Issue by sfxworks** [PhantomAppDevelopment/firebase-as3#19]
My previous plan for messaging was to set up some sort of private node in the database and have both clients connect to it in real-time. Although, I'm noticing some truncated text at times...

So! Is cloud messaging possible? What's the difference? How does it work?

**Comment by agentphantom** [comment]
I have created small chat apps that work as you described, (users join a private node with URLStream) but I don't have the problem you mentioned.

Try to debug the incoming messages to see if they are indeed complete. What I do is just to do a hard coded substring to get the 'data' part from the message packet.
