### ISSUE TITLE
Questions about URLStream

### ISSUE THREAD

**Issue by yong2khoo88** [PhantomAppDevelopment/firebase-as3#3]
First, I would like to thank you for setting up the documentation.

This may not be an issue, but there are something I am not sure about the URLStream for the Realtime Database.

Based on my testing in web using javascript, whenever there is a change in the database inside a node, it returns everything that the node contains, instead of 'only the changes'.

I would like to know, if URLStream is possible to kind of 'return everything contained by the node' in the ProgressEvent?

**Comment by agentphantom** [comment]
Hi,

Thanks for bringing this point, this is my experience on it:

When I use URLStream I listen to the ProgressEvent, it gets fired when data is modified and in regular intervals.

When nothing happens it returns a 'null' value.
When data is changed it returns a JSON with only the path and the values that were changed.

I recommend to study the SimpleChat example, specially this line which outputs the Firebase response: https://github.com/PhantomAppDevelopment/firebase-as3/blob/master/examples/SimpleChat.mxml#L150

I studied the JavaScript SDK and I found out that some methods combine the Firebase APIs with custom heuristics.

I think the JavaScript SDK creates an Array/Map with all the changes and keeps updating it with the new info that gets streamed.

My recommendation is to map the node to a Map/Object/Dictionary (depending in your target language) and modify it every time you get new data.

**Comment by yong2khoo88** [comment]
"Map the node and modify it on every ProgressEvent" before performing my own logic.

That's a brilliant idea! Thank you!

**Comment by agentphantom** [comment]
A little update:

When you use URLStream, the first response contains the complete node information. Further responses contains only the data that was changed,

I have attached an image showing how the data is being received.

![realtime](https://cloud.githubusercontent.com/assets/5375219/20248211/6e530c06-a9a4-11e6-9e9f-c6e735171afd.png)

**Comment by yong2khoo88** [comment]
Yep. I observe this as well.  Thanks :)
