### ISSUE TITLE
upload files using File.upload?

### ISSUE THREAD

**Issue by sfxworks** [PhantomAppDevelopment/firebase-as3#9]
I would like a progress bar for my uploader. I hear the only way to get progress events to fire is through file.upload. How would I do this?

**Comment by agentphantom** [comment]
I have added a new example that demonstrates how to do it.

[UploadWithProgress.mxml](https://github.com/PhantomAppDevelopment/firebase-as3/blob/master/examples/UploadWithProgress.mxml)

**Comment by sfxworks** [comment]
You're awesome.
